### ISSUE TITLE
XSLT points to GIT training slide deck

### ISSUE THREAD

**Issue by kgrons** [ablwr/avpres-training#2]
1. thank you thank you thank you thank you thank you 🙏

2. Computers > **XSLT** link points to http://training.ashleyblewer.com/presentations/git.html, not XSLT resource.

**Comment by ablwr** [comment]
Ahhh!! Thank you for pointing this out! I re-arranged the guides so now XSLT didn't even make it to the top of the list... so I accidentally resolved it before I saw this issue. Thank youu thank you
